defaultContentLanguage = "da"
publishDir = "docs"
baseURL = "http://dyeislife.dk/"
title = "dyeislife.dk"
theme = "dyeislifedk"
[params]
  description = "The number one resource for your dyeislifedk content. Come along for information around tournaments, season games, merch and everything dyeislifedk related."
  images = ["images/dyeislifedk-tietgenkollegiet-1.png"]


[languages]
  [languages.en]
    flag = "🇬🇧"
    weight = 0
  [languages.da]
    flag = "🇩🇰"
    weight = 0
