name = "dyeislifedk"
license = "MIT"
licenselink = "https://github.com/janschill/dyeislifedk/blob/master/LICENSE"
description = "DyeislifeDK Hugo theme"
homepage = "https://dyeislife.dk/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "@janschill"
  homepage = "https://janschill.de"
